Verification dl
CoVPN/correlates_reporting pull request #200
Opened 2021-03-29 18:32 UTC by dilu963

Verification is done for plots targeted for independent double programming in Immunogenicity Rport.

2021-03-29 20:00 UTC, benkeser commented
Please remove all `.rds` `.png` `.PNG` `.csv`  files from the PR and resubmit. These can be added to a `.gitignore` file or deleted.

The `renv` files also look to be modified questionably modified in places. @nhejazi want to double check me on this?

2021-03-30 00:53 UTC, benkeser commented
> Please remove all `.rds` `.png` `.PNG` `.csv` files from the PR and resubmit. These can be added to a `.gitignore` file or deleted.

You'll need to [explicitly remove these files after adding to `gitignore`](https://superuser.com/questions/1397199/how-to-ignore-a-tracked-file-in-git-without-deleting-it)

2021-03-30 01:04 UTC, dilu963 commented
Sorry, I am still trying to get familiar with GitHub. Do you mean remove these files and then recommit?

2021-03-30 01:41 UTC, benkeser commented
Can you also remove `.Rproj` and `renv.lockfile`?

2021-03-30 01:48 UTC, benkeser commented
@dilu963 looks like some merge conflicts to fix in `.gitignore`

@thebioengineer can you check that this is all good?

2021-03-30 01:51 UTC, thebioengineer commented
Sure thing. I'll take a look and get back to you!

2021-03-30 02:36 UTC, thebioengineer requested changes
Hey @dilu963 - this is looking great. Lets have a call tomorrow morning to smooth out the merge conflicts and add progammatic comparisons into the verification reports!

2021-03-30 02:36 UTC, thebioengineer commented on immuno_graphical/verification/verification_plan.Rmd
> +  html_document: default
hey @dilu963 - could you remove html_document as an output? and the html document that you produced?

2021-03-30 02:36 UTC, thebioengineer commented on cor_graphical/verification/verification_report.Rmd
> +  html_document: default
Please remove the html_document output and keep only the pdf_document output. Remove html files that were generated.

2021-03-30 02:36 UTC, thebioengineer commented on cor_graphical/verification/verification_report.Rmd
> +Outputs of Line plots, Violin plots and box plots and were visually compared to the outputs generated by primary programmer, one issue that was identified was the titer values were turncated by wrong
Please add a programmatic comparison of the input data & calculated statistics you generated against the data 
 & stats provided by kendrick. (save the input data for each plot you generated against the input data kendrick generated for each plot and compare via `identical()` or `dplyr::all_equal()`.

2021-04-05 02:15 UTC, closed without merging