Adding tests
CoVPN/correlates_reporting pull request #298
Opened 2021-05-06 15:35 UTC by benkeser

This PR implements some additional checks of the raw and processed data.

The `Makefile` command for producing the processed data has been modified to the following workflow:
- run checks on raw data
- if pass, create clean data (using @youyifong as usual)
- run checks on clean data

I have also added a `make help_tests` command to show an in-words description of the tests that have been implemented.

2021-05-06 18:25 UTC, thebioengineer requested changes
Code looks good for what is there. 

One thing I could see adding is checks for no missing-ness in the cleaned code we expect imputation to be cleaning up.

2021-05-06 18:32 UTC, benkeser commented
> One thing I could see adding is checks for no missing-ness in the cleaned code we expect imputation to be cleaning up.

Such checks are run in line 288 `data_clean/make_dat_proc.R`. @youyifong already had those checks in his script, so I just left them there. I do make a comment about them in my script so that they are described in the `make help_tests` command.

2021-05-06 18:34 UTC, thebioengineer approved these changes
Sounds like the change I wanted was already done - not sure how I missed that.

2021-05-07 06:10 UTC, youyifong commented
Thanks! A few comments based off of what is not passing.

Wstratum/tps.stratum/demo.stratum is now expected to have NA's because URMforsubcohortsampling is expected to have NA's.

## missingness in weights ## isn't passing b/c the criterion for ph1 has just been updated to include EarlyendpointD57==0. Because we have double programming, this check may not add values and will increase maintenance overhead.

2021-05-07 20:01 UTC, nhejazi approved these changes
LGTM but suggested a few minor changes throughout.

2021-05-07 20:01 UTC, nhejazi commented on data_clean/make_raw_dat_check.R
> +renv::activate()
```suggestion
renv::activate(here::here())
```

2021-05-07 20:01 UTC, nhejazi commented on data_clean/make_raw_dat_check.R
> +renv::activate()
This is also addressed in #299

2021-05-07 20:01 UTC, nhejazi commented on data_clean/make_dat_proc.R
> +      )
```suggestion
      assertthat::assert_that(
        all(complete.cases(dat.tmp.impute[dat.tmp.impute$Wstratum == w, imp.markers])),
        msg = "missing markers imputed properly in each stratum?"
      )  
```

2021-05-10 13:23 UTC, merged