Super Learner baseline risk score verification
CoVPN/correlates_reporting pull request #51
Opened 2021-02-23 02:14 UTC by benkeser

Working PR for SL verification code.

2021-03-31 15:25 UTC, thebioengineer commented
Very thorough, and lots of code!!
I like the verification report, just add:
  - we need to explain why the tolerance is acceptable. Going to meet with Paul today to discuss specific verbiage around that. 
  - Please add a table at the end for your signature ( [example](https://github.com/CoVPN/correlates_reporting/blob/109ed46059f45a3a9ae2a7f4965a30065bbb3ec2/data_clean/verification/verification_report.Rmd#L190) )

2021-03-31 18:04 UTC, nhejazi requested changes
@benkeser Very minor changes requested (see comments); everything else LGTM. Please fix these and re-run verification after the comments in #216 have been addressed. After that, should be good to merge this, and I agree with squashing the commits.

2021-03-31 18:04 UTC, nhejazi commented on base_riskscore/verification/verification_code/code/fit_superlearner.R
> +this_seed <- 20210216
For example, this line could just be used in the one of the above scripts that instead loads a set of saved seeds (only one of which is now used).

2021-03-31 18:04 UTC, nhejazi commented on base_riskscore/verification/verification_code/code/get_cv_sl_seeds.R
> +
We should remove this file and any references to the output it creates, since only a single random seed is now used.

2021-03-31 18:04 UTC, nhejazi commented on base_riskscore/verification/verification_code/code/submit_jobs.sh
> +
Seems unnecessary now since only a single seed is used, right?

2021-03-31 18:04 UTC, nhejazi commented on base_riskscore/verification/verification_code/code/submit_jobs_local.sh
> +
Seems unnecessary now since only a single seed is used, right?

2021-03-31 21:18 UTC, benkeser commented on base_riskscore/verification/verification_code/code/fit_cv_superlearner.R
> +print(paste0("Actual seed set before run is ", seeds[this_seed],"."))
I'm going to keep this code around in case we revert back to multiple seeds for the in-house runs.

2021-05-26 22:42 UTC, brborate approved these changes
This looks good. 👍

2021-06-04 15:16 UTC, benkeser commented
@nhejazi @thebioengineer, finally got around to getting full agreement on CVAUC CIs. So I think we're good to merge this?

2021-06-04 15:22 UTC, thebioengineer commented
Could you include a PDF showing that the results are identical, then yeah, I think this is Good to Go!

2021-06-04 15:22 UTC, benkeser commented
> Could you include a PDF showing that the results are identical

0405526 includes report

2021-06-04 15:23 UTC, thebioengineer approved these changes

2021-06-04 15:23 UTC, thebioengineer commented
> > Could you include a PDF showing that the results are identical
> 
> [0405526](https://github.com/CoVPN/correlates_reporting/commit/0405526fc1f266c3c037053272f42b274982225d) includes report

I think we simultaneously posted/commented. I deleted that comment, looks good.

2021-06-04 18:02 UTC, merged